apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: grafana
  name: grafana 
spec:
  ports:
  - name: grafana
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana