apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simonsDemoAKS-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User # recommended to use "Group" in production 
#  name: 7cb2eb4f-37d4-485c-ab5a-822eaae59025 # use either UPN if AKS is in same tenant as users - or use objectId if aks is in another tenant as user
  name: df0414da-d62a-4343-9791-cad5a12f874c