# details see: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # ClusterRoleBinding grants permission at the cluster level and in all namespaces
metadata:
  name: simonsDemoAKS-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: cluster-admin # must match a pre-defined role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User # recommended to use "Group" in production 
#  name: 7cb2eb4f-37d4-485c-ab5a-822eaae59025 # use either UPN if AKS is in same tenant as users - or use objectId if aks is in another tenant as user
  name: df0414da-d62a-4343-9791-cad5a12f874c